[SQUASH]sm8250-common: Bringup for Upsidedowncake(android-14)
sm8250-common: added prebuilt android.hardware.sensors (2.0 and 2.1)

sm8250-common: added PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true flag

sm8250-common: added patched libprotobuff-cpp from stock

sm8250-common: Disable sparse image build on ext fs

We use ext4 type. Sparse image cause mounting issue

Signed-off-by: Master <mhmdeveloperofficial@gmail.com>

sm8250-common: Enable adb on boot

sm8250-common: Switch to AOSP encryption

* From redfin-user 12 SPB5.210812.002 7671067 release-keys

Change-Id: I20d40c93b3861a92716165ab90bb09c73c0e64ed
Signed-off-by: SathamHussainM <sathamhussain.m11@gmail.com>

sm8250-common: Remove deprecated flag

sm8250-common: Set BUILD_BROKEN_CLANG_PROPERTY := true

* QCOM HALs need it

Signed-off-by: Leonardo Ledda <leonardoledda@gmail.com>

sm8250-common: Add more fqnames in DFM

sm8250-common: vibrator: add proper identation

device/xiaomi/sm8250-common/vibrator/Vibrator.cpp

device/xiaomi/sm8250-common/vibrator/Vibrator.cpp:196:13: error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation]
            return 0;
            ^
device/xiaomi/sm8250-common/vibrator/Vibrator.cpp:194:9: note: previous statement is here
        if (playLengthMs != NULL)
        ^
1 error generated.

Revert "sm8250-common: Enable Project ID Quota support on userdata."

This reverts commit 23d57c7f27ba83337c84cb17429a5b734fb3a84a.

Co-Authored-By: Yoriscape <36034638+yoriscape@users.noreply.github.com>